import { dirname } from "path";
import { fileURLToPath } from "url";
import { FlatCompat } from "@eslint/eslintrc";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const compat = new FlatCompat({
  baseDirectory: __dirname,
});

const eslintConfig = [
  ...compat.extends("next/core-web-vitals"),
  {
    rules: {
      // Disable all ESLint rules
      "@typescript-eslint/no-unused-vars": "off",
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-empty-function": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "react/no-unescaped-entities": "off",
      "react/display-name": "off",
      "react-hooks/exhaustive-deps": "off",
      "no-unused-vars": "off",
      "no-console": "off",
      "no-debugger": "off",
      "prefer-const": "off",
      "no-var": "off",
      "no-undef": "off",
      "no-redeclare": "off",
      "no-duplicate-imports": "off",
      "no-empty": "off",
      "no-extra-semi": "off",
      "no-irregular-whitespace": "off",
      "no-mixed-spaces-and-tabs": "off",
      "no-trailing-spaces": "off",
      "no-unreachable": "off",
      "no-useless-escape": "off",
      "valid-typeof": "off",
      "no-case-declarations": "off",
      "no-constant-condition": "off",
      "no-empty-pattern": "off",
      "no-fallthrough": "off",
      "no-global-assign": "off",
      "no-import-assign": "off",
      "no-inner-declarations": "off",
      "no-invalid-regexp": "off",
      "no-obj-calls": "off",
      "no-prototype-builtins": "off",
      "no-regex-spaces": "off",
      "no-sparse-arrays": "off",
      "no-unexpected-multiline": "off",
      "use-isnan": "off",
      "no-cond-assign": "off",
      "no-dupe-args": "off",
      "no-dupe-keys": "off",
      "no-duplicate-case": "off",
      "no-empty-character-class": "off",
      "no-ex-assign": "off",
      "no-extra-boolean-cast": "off",
      "no-extra-parens": "off",
      "no-func-assign": "off",
      "no-invalid-this": "off",
      "no-new-symbol": "off",
      "no-unsafe-finally": "off",
      "no-unsafe-negation": "off",
      "require-yield": "off",
      "constructor-super": "off",
      "no-class-assign": "off",
      "no-const-assign": "off",
      "no-dupe-class-members": "off",
      "no-new-target": "off",
      "no-this-before-super": "off",
      "no-useless-constructor": "off",
      "no-useless-return": "off",
      "prefer-promise-reject-errors": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "prefer-template": "off",
      "rest-spread-spacing": "off",
      "template-curly-spacing": "off",
      "yield-star-spacing": "off",
      "array-bracket-spacing": "off",
      "block-spacing": "off",
      "brace-style": "off",
      "camelcase": "off",
      "comma-dangle": "off",
      "comma-spacing": "off",
      "comma-style": "off",
      "computed-property-spacing": "off",
      "func-call-spacing": "off",
      "indent": "off",
      "key-spacing": "off",
      "keyword-spacing": "off",
      "lines-around-comment": "off",
      "lines-between-class-members": "off",
      "max-len": "off",
      "max-lines": "off",
      "max-lines-per-function": "off",
      "max-params": "off",
      "max-statements": "off",
      "multiline-comment-style": "off",
      "new-cap": "off",
      "new-parens": "off",
      "newline-per-chained-call": "off",
      "no-array-constructor": "off",
      "no-bitwise": "off",
      "no-continue": "off",
      "no-inline-comments": "off",
      "no-lonely-if": "off",
      "no-multi-assign": "off",
      "no-multiple-empty-lines": "off",
      "no-negated-condition": "off",
      "no-nested-ternary": "off",
      "no-new-object": "off",
      "no-plusplus": "off",
      "no-tabs": "off",
      "no-ternary": "off",
      "no-underscore-dangle": "off",
      "no-unneeded-ternary": "off",
      "no-whitespace-before-property": "off",
      "nonblock-statement-body-position": "off",
      "object-curly-newline": "off",
      "object-curly-spacing": "off",
      "object-property-newline": "off",
      "one-var": "off",
      "one-var-declaration-per-line": "off",
      "operator-assignment": "off",
      "operator-linebreak": "off",
      "padded-blocks": "off",
      "padding-line-between-statements": "off",
      "quote-props": "off",
      "quotes": "off",
      "semi": "off",
      "semi-spacing": "off",
      "semi-style": "off",
      "space-before-blocks": "off",
      "space-before-function-paren": "off",
      "space-in-parens": "off",
      "space-infix-ops": "off",
      "space-unary-ops": "off",
      "spaced-comment": "off",
      "switch-colon-spacing": "off",
      "template-tag-spacing": "off",
      "unicode-bom": "off",
      "wrap-regex": "off",
      "arrow-body-style": "off",
      "arrow-parens": "off",
      "arrow-spacing": "off",
      "generator-star-spacing": "off",
      "no-confusing-arrow": "off",
      "no-duplicate-imports": "off",
      "no-useless-computed-key": "off",
      "no-useless-rename": "off",
      "no-var": "off",
      "object-shorthand": "off",
      "prefer-arrow-callback": "off",
      "prefer-const": "off",
      "prefer-destructuring": "off",
      "prefer-numeric-literals": "off",
      "prefer-rest-params": "off",
      "prefer-spread": "off",
      "prefer-template": "off",
      "rest-spread-spacing": "off",
      "sort-imports": "off",
      "symbol-description": "off",
      "template-curly-spacing": "off",
      "yield-star-spacing": "off"
    }
  }
];

export default eslintConfig;
